### ISSUE TITLE
User Story

### ISSUE THREAD

**Issue by bryanrkelley** [StudyBuddies-UW2018/HopOn#6]
## User Story
As a user, I want eat food truck food so that I can experience fun new food options that are nearby.

## Acceptance Criteria
- [ ] index.html has submit button linked to geolocation API

- [ ] Create radius limit of 1 mile for food trucks

- [ ]  On submit, save user's location and show all available trucks in the radius

- [ ]  Compare the user's location against distance to each food truck

- [ ]  Order trucks based on distance from user

**Comment by NW91** [comment]
no longer applicable, different app idea
